//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PMS.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class ExpenseCategory
    {
        public int id { get; set; }
        public string ExpenseCategory1 { get; set; }
        public int Parent { get; set; }
        public bool IsActive { get; set; }
    }
}
