//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PMS.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class expense
    {
        public int id { get; set; }
        public Nullable<System.DateTime> Expense_Date { get; set; }
        public Nullable<int> Branch_Id { get; set; }
        public Nullable<int> Company_Id { get; set; }
        public Nullable<int> Expense_Category_Id { get; set; }
        public Nullable<int> Expense_Item_Id { get; set; }
        public Nullable<decimal> Amount { get; set; }
        public Nullable<System.DateTime> Created_Date { get; set; }
        public Nullable<System.Guid> Created_By { get; set; }
        public Nullable<System.DateTime> Modified_Date { get; set; }
        public Nullable<System.Guid> Modified_By { get; set; }
        public Nullable<int> bank_id { get; set; }
        public string cheque_number { get; set; }
        public string remarks { get; set; }
        public string Pay_To { get; set; }
    }
}
