//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PMS.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class loansDetail
    {
        public int Id { get; set; }
        public int loan_Id { get; set; }
        public int project_id { get; set; }
        public decimal amount { get; set; }
        public System.Guid created_by { get; set; }
        public System.DateTime created_on { get; set; }
        public System.Guid updated_by { get; set; }
        public System.DateTime updated_on { get; set; }
        public bool isactive { get; set; }
        public Nullable<int> supplierinvoice_item_id { get; set; }
        public virtual loan loan { get; set; }
    }
}
