//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PMS.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class payment_detail
    {
        public long id { get; set; }
        public int payment_id { get; set; }
        public int supplierinvoice_item_id { get; set; }
        public Nullable<decimal> agreed_amount { get; set; }
        public Nullable<decimal> payment_amount { get; set; }
    }
}
