//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PMS.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class additions_omissions
    {
        public long id { get; set; }
        public System.DateTime date { get; set; }
        public long project_id { get; set; }
        public Nullable<int> record_type { get; set; }
        public string addition_omissioni_description { get; set; }
        public Nullable<decimal> amount { get; set; }
        public Nullable<decimal> gst_percentage { get; set; }
        public Nullable<decimal> gst_amount { get; set; }
        public Nullable<decimal> total_amount { get; set; }
        public string remarks { get; set; }
        public System.DateTime created_date { get; set; }
        public System.DateTime modified_date { get; set; }
        public System.Guid created_by { get; set; }
        public System.Guid modified_by { get; set; }
        public bool isactive { get; set; }
    }
}
namespace PMS.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class AspNetRole
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public AspNetRole()
        {
            this.AspNetUsers = new HashSet<AspNetUser>();
        }
    
        public string Id { get; set; }
        public string Name { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AspNetUser> AspNetUsers { get; set; }
    }
}
namespace PMS.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class AspNetUser
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public AspNetUser()
        {
            this.AspNetUserClaims = new HashSet<AspNetUserClaim>();
            this.AspNetUserLogins = new HashSet<AspNetUserLogin>();
            this.AspNetRoles = new HashSet<AspNetRole>();
        }
    
        public string Id { get; set; }
        public string Email { get; set; }
        public bool EmailConfirmed { get; set; }
        public string PasswordHash { get; set; }
        public string SecurityStamp { get; set; }
        public string PhoneNumber { get; set; }
        public bool PhoneNumberConfirmed { get; set; }
        public bool TwoFactorEnabled { get; set; }
        public Nullable<System.DateTime> LockoutEndDateUtc { get; set; }
        public bool LockoutEnabled { get; set; }
        public int AccessFailedCount { get; set; }
        public string UserName { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AspNetUserClaim> AspNetUserClaims { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AspNetUserLogin> AspNetUserLogins { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AspNetRole> AspNetRoles { get; set; }
    }
}
namespace PMS.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class AspNetUserClaim
    {
        public int Id { get; set; }
        public string UserId { get; set; }
        public string ClaimType { get; set; }
        public string ClaimValue { get; set; }
    
        public virtual AspNetUser AspNetUser { get; set; }
    }
}
namespace PMS.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class AspNetUserLogin
    {
        public string LoginProvider { get; set; }
        public string ProviderKey { get; set; }
        public string UserId { get; set; }
    
        public virtual AspNetUser AspNetUser { get; set; }
    }
}
namespace PMS.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class bank
    {
        public int id { get; set; }
        public string bank_name { get; set; }
        public string account_number { get; set; }
        public string branch_code { get; set; }
        public string bank_code { get; set; }
        public string swif_code { get; set; }
        public string payment_instructions { get; set; }
        public string additional_remarks { get; set; }
        public string address1 { get; set; }
        public string address2 { get; set; }
        public string address3 { get; set; }
        public string address4 { get; set; }
        public string zip_code { get; set; }
        public string email { get; set; }
        public string website { get; set; }
        public string phone { get; set; }
        public string mobile { get; set; }
        public string contact_person { get; set; }
        public System.DateTime created_date { get; set; }
        public Nullable<System.Guid> created_by { get; set; }
        public System.DateTime modified_date { get; set; }
        public Nullable<System.Guid> modified_by { get; set; }
        public bool isactive { get; set; }
        public Nullable<int> branch_id { get; set; }
    }
}
namespace PMS.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class branch
    {
        public long id { get; set; }
        public long company_id { get; set; }
        public string branch_name { get; set; }
        public string company_initial { get; set; }
        public string address1 { get; set; }
        public string address2 { get; set; }
        public string address3 { get; set; }
        public string address4 { get; set; }
        public string zip_code { get; set; }
        public string email { get; set; }
        public string website { get; set; }
        public string phone { get; set; }
        public string mobile { get; set; }
        public string fax { get; set; }
        public string contact_person { get; set; }
        public Nullable<long> country_id { get; set; }
        public string company_reg_no { get; set; }
        public string gst_reg_no { get; set; }
        public System.DateTime created_date { get; set; }
        public Nullable<System.Guid> created_by { get; set; }
        public System.DateTime modified_date { get; set; }
        public Nullable<System.Guid> modified_by { get; set; }
        public bool isactive { get; set; }
    }
}
namespace PMS.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class C__MigrationHistory
    {
        public string MigrationId { get; set; }
        public string ContextKey { get; set; }
        public byte[] Model { get; set; }
        public string ProductVersion { get; set; }
    }
}
namespace PMS.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class company
    {
        public long id { get; set; }
        public string company_name { get; set; }
        public string company_initial { get; set; }
        public string address1 { get; set; }
        public string address2 { get; set; }
        public string address3 { get; set; }
        public string address4 { get; set; }
        public string zip_code { get; set; }
        public string email { get; set; }
        public string website { get; set; }
        public string phone { get; set; }
        public string mobile { get; set; }
        public string fax { get; set; }
        public string contact_person { get; set; }
        public string reg_no { get; set; }
        public string gst_reg_no { get; set; }
        public System.DateTime created_date { get; set; }
        public Nullable<System.Guid> created_by { get; set; }
        public System.DateTime modified_date { get; set; }
        public Nullable<System.Guid> modified_by { get; set; }
        public bool isactive { get; set; }
    }
}
namespace PMS.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class country
    {
        public long id { get; set; }
        public string name { get; set; }
        public string code { get; set; }
    }
}
namespace PMS.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class customer
    {
        public long id { get; set; }
        public string name1 { get; set; }
        public string name2 { get; set; }
        public string nric1 { get; set; }
        public string nric2 { get; set; }
        public string block_no { get; set; }
        public string job_site { get; set; }
        public string address { get; set; }
        public string contact_person { get; set; }
        public string email { get; set; }
        public string phone { get; set; }
        public string mobile { get; set; }
        public Nullable<bool> gst_registered { get; set; }
        public string gst_no { get; set; }
        public System.DateTime created_date { get; set; }
        public Nullable<System.Guid> created_by { get; set; }
        public System.DateTime modified_date { get; set; }
        public Nullable<System.Guid> modified_by { get; set; }
        public bool isactive { get; set; }
    }
}
namespace PMS.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class designer_receipt_detail
    {
        public long id { get; set; }
        public Nullable<long> receipt_id { get; set; }
        public Nullable<int> invoice_id { get; set; }
        public Nullable<decimal> amount { get; set; }
        public Nullable<decimal> gst_percentage { get; set; }
        public Nullable<decimal> gst_amount { get; set; }
        public Nullable<decimal> total_amount { get; set; }
    }
}
namespace PMS.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class designer_receipts
    {
        public long id { get; set; }
        public Nullable<System.DateTime> receipt_date { get; set; }
        public Nullable<int> mode_of_payment_id { get; set; }
        public Nullable<int> bank_id { get; set; }
        public string cheque_details { get; set; }
        public string designer_name { get; set; }
        public Nullable<long> branch_id { get; set; }
        public string remarks { get; set; }
        public System.DateTime created_date { get; set; }
        public Nullable<System.Guid> created_by { get; set; }
        public System.DateTime modified_date { get; set; }
        public Nullable<System.Guid> modified_by { get; set; }
        public bool isactive { get; set; }
    }
}
namespace PMS.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class expense
    {
        public int id { get; set; }
        public Nullable<System.DateTime> Expense_Date { get; set; }
        public Nullable<int> Branch_Id { get; set; }
        public Nullable<int> Company_Id { get; set; }
        public Nullable<int> Expense_Category_Id { get; set; }
        public Nullable<int> Expense_Item_Id { get; set; }
        public Nullable<decimal> Amount { get; set; }
        public Nullable<System.DateTime> Created_Date { get; set; }
        public Nullable<System.Guid> Created_By { get; set; }
        public Nullable<System.DateTime> Modified_Date { get; set; }
        public Nullable<System.Guid> Modified_By { get; set; }
        public Nullable<int> bank_id { get; set; }
        public string cheque_number { get; set; }
        public string remarks { get; set; }
        public string Pay_To { get; set; }
    }
}
namespace PMS.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class ExpenseCategory
    {
        public int id { get; set; }
        public string ExpenseCategory1 { get; set; }
        public int Parent { get; set; }
        public Nullable<bool> IsActive { get; set; }
    }
}
namespace PMS.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class loan
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public loan()
        {
            this.loansDetails = new HashSet<loansDetail>();
        }
    
        public int Id { get; set; }
        public int branch_Id { get; set; }
        public System.DateTime LoanDate { get; set; }
        public int rec_type { get; set; }
        public long person_id { get; set; }
        public string person_type { get; set; }
        public string purpose { get; set; }
        public int payment_mode { get; set; }
        public Nullable<int> bank_id { get; set; }
        public string cheque_number { get; set; }
        public decimal amount { get; set; }
        public System.Guid created_by { get; set; }
        public System.DateTime created_on { get; set; }
        public System.Guid updated_by { get; set; }
        public System.DateTime updated_on { get; set; }
        public bool isactive { get; set; }
        public Nullable<int> supplier_payment_Id { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<loansDetail> loansDetails { get; set; }
    }
}
namespace PMS.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class loansDetail
    {
        public int Id { get; set; }
        public int loan_Id { get; set; }
        public int project_id { get; set; }
        public decimal amount { get; set; }
        public System.Guid created_by { get; set; }
        public System.DateTime created_on { get; set; }
        public System.Guid updated_by { get; set; }
        public System.DateTime updated_on { get; set; }
        public bool isactive { get; set; }
        public Nullable<int> supplierinvoice_item_id { get; set; }
    
        public virtual loan loan { get; set; }
    }
}
namespace PMS.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class mode_of_payment
    {
        public int id { get; set; }
        public string mode_of_payment1 { get; set; }
    }
}
namespace PMS.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class payment
    {
        public long id { get; set; }
        public Nullable<System.DateTime> payment_date { get; set; }
        public long supplier_id { get; set; }
        public int bank_id { get; set; }
        public string cheque_number { get; set; }
        public Nullable<decimal> rebate_amount { get; set; }
        public Nullable<decimal> paid_amount { get; set; }
        public string remarks { get; set; }
        public System.DateTime created_date { get; set; }
        public Nullable<System.Guid> created_by { get; set; }
        public System.DateTime modified_date { get; set; }
        public Nullable<System.Guid> modified_by { get; set; }
        public Nullable<int> payment_mode { get; set; }
        public bool isactive { get; set; }
        public Nullable<System.DateTime> collection_date { get; set; }
    }
}
namespace PMS.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class payment_detail
    {
        public long id { get; set; }
        public int payment_id { get; set; }
        public int supplierinvoice_item_id { get; set; }
        public Nullable<decimal> agreed_amount { get; set; }
        public Nullable<decimal> payment_amount { get; set; }
    }
}
namespace PMS.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class project
    {
        public long id { get; set; }
        public Nullable<System.DateTime> contract_date { get; set; }
        public string project_number { get; set; }
        public string project_name { get; set; }
        public Nullable<System.DateTime> project_start_date { get; set; }
        public Nullable<long> salesmen_id { get; set; }
        public Nullable<long> branch_id { get; set; }
        public long customer_id { get; set; }
        public Nullable<decimal> contract_amount { get; set; }
        public Nullable<decimal> gst_percentage { get; set; }
        public Nullable<decimal> gst_amount { get; set; }
        public Nullable<decimal> total_amount { get; set; }
        public int bank_id { get; set; }
        public int status_id { get; set; }
        public string remarks { get; set; }
        public System.DateTime created_date { get; set; }
        public Nullable<System.Guid> created_by { get; set; }
        public System.DateTime modified_date { get; set; }
        public Nullable<System.Guid> modified_by { get; set; }
        public bool isactive { get; set; }
        public Nullable<decimal> saleman_commission { get; set; }
    
        public virtual project projects1 { get; set; }
        public virtual project project1 { get; set; }
    }
}
namespace PMS.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class project_status
    {
        public int id { get; set; }
        public string project_status1 { get; set; }
    }
}
namespace PMS.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class receipt
    {
        public long id { get; set; }
        public Nullable<System.DateTime> receipt_date { get; set; }
        public Nullable<int> customer_id { get; set; }
        public Nullable<int> mode_of_payment_id { get; set; }
        public Nullable<int> bank_id { get; set; }
        public string cheque_details { get; set; }
        public Nullable<long> sales_man_id { get; set; }
        public Nullable<long> branch_id { get; set; }
        public string remarks { get; set; }
        public System.DateTime created_date { get; set; }
        public Nullable<System.Guid> created_by { get; set; }
        public System.DateTime modified_date { get; set; }
        public Nullable<System.Guid> modified_by { get; set; }
        public bool isactive { get; set; }
    }
}
namespace PMS.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class receipt_detail
    {
        public long id { get; set; }
        public Nullable<long> receipt_id { get; set; }
        public Nullable<long> project_id { get; set; }
        public Nullable<int> invoice_id { get; set; }
        public Nullable<decimal> amount { get; set; }
        public Nullable<decimal> gst_percentage { get; set; }
        public Nullable<decimal> gst_amount { get; set; }
        public Nullable<decimal> total_amount { get; set; }
    }
}
namespace PMS.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class salesman
    {
        public long id { get; set; }
        public long branch_Id { get; set; }
        public string salesmen_name { get; set; }
        public string address1 { get; set; }
        public string address2 { get; set; }
        public string address3 { get; set; }
        public string address4 { get; set; }
        public string zip_code { get; set; }
        public string email { get; set; }
        public string website { get; set; }
        public string phone { get; set; }
        public string mobile { get; set; }
        public System.DateTime created_date { get; set; }
        public Nullable<System.Guid> created_by { get; set; }
        public System.DateTime modified_date { get; set; }
        public Nullable<System.Guid> modified_by { get; set; }
        public bool isactive { get; set; }
        public Nullable<decimal> saleman_commission { get; set; }
        public string remarks { get; set; }
    }
}
namespace PMS.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class status
    {
        public int id { get; set; }
        public string status1 { get; set; }
    }
}
namespace PMS.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class supplier
    {
        public long id { get; set; }
        public string supplier_name { get; set; }
        public string address1 { get; set; }
        public string address2 { get; set; }
        public string address3 { get; set; }
        public string address4 { get; set; }
        public string zip_code { get; set; }
        public string email { get; set; }
        public string website { get; set; }
        public string phone { get; set; }
        public string mobile { get; set; }
        public string contact_person { get; set; }
        public string nric_no { get; set; }
        public Nullable<bool> gst_registered { get; set; }
        public string gst_no { get; set; }
        public System.DateTime created_date { get; set; }
        public Nullable<System.Guid> created_by { get; set; }
        public System.DateTime modified_date { get; set; }
        public Nullable<System.Guid> modified_by { get; set; }
        public bool isactive { get; set; }
        public Nullable<decimal> rebate_per { get; set; }
    }
}
namespace PMS.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_contract_types
    {
        public int Id { get; set; }
        public string contract_type { get; set; }
    }
}
namespace PMS.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_designer_invoice
    {
        public int Id { get; set; }
        public Nullable<int> Company_id { get; set; }
        public string Designer_name { get; set; }
        public System.DateTime Invoice_date { get; set; }
        public string Invoice_number { get; set; }
        public int Payment_terms { get; set; }
        public Nullable<int> Contract_type { get; set; }
        public Nullable<bool> is_tax { get; set; }
        public Nullable<decimal> tax { get; set; }
        public System.DateTime created_date { get; set; }
        public System.Guid created_by { get; set; }
        public System.DateTime modification_date { get; set; }
        public System.Guid modification_by { get; set; }
        public Nullable<decimal> tax_amount { get; set; }
    }
}
namespace PMS.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_designerinvoice_items
    {
        public int Id { get; set; }
        public int invoice_id { get; set; }
        public string Contract_number { get; set; }
        public string item_description { get; set; }
        public decimal item_amount { get; set; }
    }
}
namespace PMS.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_invoice
    {
        public int Id { get; set; }
        public Nullable<int> Company_id { get; set; }
        public int Bill_to { get; set; }
        public System.DateTime Invoice_date { get; set; }
        public string Invoice_number { get; set; }
        public int Sales_person { get; set; }
        public int Payment_terms { get; set; }
        public Nullable<int> Contract_type { get; set; }
        public Nullable<bool> is_tax { get; set; }
        public Nullable<decimal> tax { get; set; }
        public System.DateTime created_date { get; set; }
        public System.Guid created_by { get; set; }
        public System.DateTime modification_date { get; set; }
        public System.Guid modification_by { get; set; }
        public Nullable<decimal> tax_amount { get; set; }
    }
}
namespace PMS.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_invoice_items
    {
        public int invoice_id { get; set; }
        public Nullable<int> project_id { get; set; }
        public string Contract_number { get; set; }
        public string item_description { get; set; }
        public decimal item_amount { get; set; }
    }
}
namespace PMS.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_payment_terms
    {
        public int Id { get; set; }
        public string payment_term { get; set; }
        public Nullable<int> payment_days { get; set; }
    }
}
namespace PMS.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_supplier_invoice
    {
        public int Id { get; set; }
        public Nullable<int> Company_id { get; set; }
        public System.DateTime invoice_date { get; set; }
        public int supplier_id { get; set; }
        public System.DateTime creation_date { get; set; }
        public System.Guid created_by { get; set; }
        public System.DateTime modification_date { get; set; }
        public System.Guid modified_by { get; set; }
    }
}
namespace PMS.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_supplierinvoice_items
    {
        public int Id { get; set; }
        public int invoice_id { get; set; }
        public int salesperson_id { get; set; }
        public int project_id { get; set; }
        public string invoice_number { get; set; }
        public Nullable<decimal> gst { get; set; }
        public Nullable<decimal> invoice_amt_without_gst { get; set; }
        public Nullable<decimal> invoice_amt_with_gst { get; set; }
        public Nullable<decimal> agreed_amt_without_gst { get; set; }
        public Nullable<decimal> agreed_amt { get; set; }
    }
}
namespace PMS.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class user_access_rights
    {
        public long id { get; set; }
        public System.Guid user_id { get; set; }
        public long branch_id { get; set; }
        public System.DateTime created_date { get; set; }
        public System.Guid created_by { get; set; }
        public System.DateTime modified_date { get; set; }
        public System.Guid modified_by { get; set; }
        public bool isactive { get; set; }
    }
}
namespace PMS.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class user_detail
    {
        public long did { get; set; }
        public System.Guid user_id { get; set; }
        public Nullable<int> company_id { get; set; }
        public string Name { get; set; }
        public string address1 { get; set; }
        public string address2 { get; set; }
        public string address3 { get; set; }
        public string address4 { get; set; }
        public string zip_code { get; set; }
        public string website { get; set; }
        public string mobile { get; set; }
        public string phone { get; set; }
        public Nullable<int> country_id { get; set; }
        public Nullable<bool> is_active { get; set; }
        public Nullable<System.DateTime> created_date { get; set; }
        public Nullable<System.Guid> created_by { get; set; }
        public Nullable<System.DateTime> modified_date { get; set; }
        public Nullable<System.Guid> modified_by { get; set; }
    }
}
namespace PMS.Database
{
    using System;
    
    public partial class SSP_BankChequeReport_Result
    {
        public string payment_date { get; set; }
        public string cheque_number { get; set; }
        public decimal rebate_amount { get; set; }
        public Nullable<decimal> PaymentAmount { get; set; }
        public string supplier_name { get; set; }
        public Nullable<decimal> paid_amount { get; set; }
    }
}
namespace PMS.Database
{
    using System;
    
    public partial class SSP_Banks_Result
    {
        public Nullable<long> Rk { get; set; }
        public int id { get; set; }
        public string bank_name { get; set; }
        public string account_number { get; set; }
        public string branch_code { get; set; }
        public string email { get; set; }
        public string phone { get; set; }
        public string branch_name { get; set; }
        public string zip_code { get; set; }
        public bool isactive { get; set; }
        public Nullable<long> TotalRecords { get; set; }
    }
}
namespace PMS.Database
{
    using System;
    
    public partial class SSP_Branches_Result
    {
        public Nullable<long> Rk { get; set; }
        public long id { get; set; }
        public string branch_name { get; set; }
        public string email { get; set; }
        public string phone { get; set; }
        public string gst_reg_no { get; set; }
        public string company_name { get; set; }
        public bool isactive { get; set; }
        public Nullable<long> TotalRecords { get; set; }
    }
}
namespace PMS.Database
{
    using System;
    
    public partial class SSP_Company_Result
    {
        public Nullable<long> Rk { get; set; }
        public long id { get; set; }
        public string company_name { get; set; }
        public string email { get; set; }
        public string phone { get; set; }
        public string reg_no { get; set; }
        public bool isactive { get; set; }
        public Nullable<long> TotalRecords { get; set; }
    }
}
namespace PMS.Database
{
    using System;
    
    public partial class SSP_Customer_Result
    {
        public Nullable<long> Rk { get; set; }
        public long id { get; set; }
        public string name1 { get; set; }
        public string nric1 { get; set; }
        public string block_no { get; set; }
        public string job_site { get; set; }
        public string gst_no { get; set; }
        public bool isactive { get; set; }
        public Nullable<long> TotalRecords { get; set; }
    }
}
namespace PMS.Database
{
    using System;
    
    public partial class SSP_CustomerInvoiceReport_Result
    {
        public int Id { get; set; }
        public System.DateTime Invoice_date { get; set; }
        public string Invoice_number { get; set; }
        public string customer_name { get; set; }
        public string company_name { get; set; }
        public string salesmen_name { get; set; }
        public decimal tax { get; set; }
        public Nullable<bool> is_tax { get; set; }
        public string Total { get; set; }
        public string Items { get; set; }
    }
}
namespace PMS.Database
{
    using System;
    
    public partial class SSP_DesignerInvoiceReport_Result
    {
        public string receipt_date { get; set; }
        public string cheque_details { get; set; }
        public string Designer_name { get; set; }
        public Nullable<int> mode_of_payment_id { get; set; }
        public string mode_of_payment_name { get; set; }
        public Nullable<decimal> amount { get; set; }
        public string invoice_numbers { get; set; }
        public string invoice_amount_items { get; set; }
        public Nullable<bool> is_tax { get; set; }
        public decimal tax { get; set; }
        public Nullable<System.DateTime> ReceiptDate { get; set; }
        public decimal tax_amount { get; set; }
        public Nullable<int> invoiceId { get; set; }
    }
}
namespace PMS.Database
{
    using System;
    
    public partial class SSP_DesignerInvoices_Result
    {
        public int Id { get; set; }
        public string Invoice_number { get; set; }
        public decimal tax_amount { get; set; }
        public System.DateTime Invoicedate { get; set; }
        public string Invoice_date { get; set; }
        public string designer_name { get; set; }
        public string CreatedUpdated { get; set; }
        public string company_name { get; set; }
        public decimal tax { get; set; }
        public Nullable<bool> is_tax { get; set; }
        public Nullable<long> Rk { get; set; }
        public Nullable<long> TotalRecords { get; set; }
        public string Total { get; set; }
        public string Items { get; set; }
    }
}
namespace PMS.Database
{
    using System;
    
    public partial class SSP_DesignerInvoiceWithAndWithoutPayment_Result
    {
        public string Invoice_date { get; set; }
        public string Designer_name { get; set; }
        public string invoice_numbers { get; set; }
        public string invoice_amount_items { get; set; }
        public Nullable<bool> is_tax { get; set; }
        public decimal tax { get; set; }
        public decimal tax_amount { get; set; }
        public int invoiceId { get; set; }
    }
}
namespace PMS.Database
{
    using System;
    
    public partial class SSP_DesignerReceiptById_Result
    {
        public Nullable<System.DateTime> receipt_date { get; set; }
        public string mode_of_payment { get; set; }
        public string branch_name { get; set; }
        public string branch_address { get; set; }
        public string branch_zip_code { get; set; }
        public Nullable<decimal> total_amount { get; set; }
    }
}
namespace PMS.Database
{
    using System;
    
    public partial class SSP_DesignerReceiptDetailByReceiptId_Result
    {
        public string invoice_number { get; set; }
        public decimal total_amount { get; set; }
    }
}
namespace PMS.Database
{
    using System;
    
    public partial class SSP_DesignerReceipts_Result
    {
        public long id { get; set; }
        public string designer_name { get; set; }
        public Nullable<System.DateTime> receiptdate { get; set; }
        public string receipt_date { get; set; }
        public string receipt_detail { get; set; }
        public string mode_of_payment { get; set; }
        public string bank_name { get; set; }
        public string cheque_details { get; set; }
        public string remarks { get; set; }
        public string CreatedUpdated { get; set; }
        public Nullable<long> Rk { get; set; }
        public Nullable<long> TotalRecords { get; set; }
    }
}
namespace PMS.Database
{
    using System;
    
    public partial class SSP_DesignerReceiptsDetailById_Result
    {
        public string Bank_Name { get; set; }
        public long id { get; set; }
        public Nullable<System.DateTime> receipt_date { get; set; }
        public string mode_of_payment { get; set; }
        public Nullable<int> bank_id { get; set; }
        public string cheque_details { get; set; }
        public string remarks { get; set; }
        public string branch_name { get; set; }
        public string branch_address { get; set; }
        public Nullable<decimal> amount { get; set; }
        public Nullable<decimal> gst_amount { get; set; }
        public Nullable<decimal> gst_percentage { get; set; }
        public Nullable<decimal> total_amount { get; set; }
        public string Invoice_number { get; set; }
        public Nullable<int> Payment_terms { get; set; }
        public Nullable<System.DateTime> Invoice_date { get; set; }
        public string payment_term { get; set; }
        public Nullable<int> payment_days { get; set; }
        public string designer_name { get; set; }
        public string contract_type { get; set; }
    }
}
namespace PMS.Database
{
    using System;
    
    public partial class SSP_EXCategory_Result
    {
        public Nullable<long> Rk { get; set; }
        public int id { get; set; }
        public string ExpenseCategory { get; set; }
        public string Parentname { get; set; }
        public int Parent { get; set; }
        public Nullable<long> TotalRecords { get; set; }
        public bool IsActive { get; set; }
    }
}
namespace PMS.Database
{
    using System;
    
    public partial class SSP_Expense_Result
    {
        public Nullable<long> Rk { get; set; }
        public int id { get; set; }
        public string ExpenseCategory { get; set; }
        public string Expense_Date { get; set; }
        public string company_name { get; set; }
        public string CreatedUpdated { get; set; }
        public string BankName { get; set; }
        public string ChequeNumber { get; set; }
        public Nullable<long> TotalRecords { get; set; }
    }
}
namespace PMS.Database
{
    using System;
    
    public partial class SSP_ExpenseReport_Result
    {
        public Nullable<int> year { get; set; }
        public string Category { get; set; }
        public string CategoryItem { get; set; }
        public int categoryId { get; set; }
        public Nullable<decimal> jan { get; set; }
        public Nullable<decimal> feb { get; set; }
        public Nullable<decimal> mar { get; set; }
        public Nullable<decimal> apr { get; set; }
        public Nullable<decimal> may { get; set; }
        public Nullable<decimal> jun { get; set; }
        public Nullable<decimal> jul { get; set; }
        public Nullable<decimal> aug { get; set; }
        public Nullable<decimal> sep { get; set; }
        public Nullable<decimal> oct { get; set; }
        public Nullable<decimal> nov { get; set; }
        public Nullable<decimal> dec { get; set; }
    }
}
namespace PMS.Database
{
    using System;
    
    public partial class SSP_GetAllBank_Result
    {
        public int id { get; set; }
        public string Bank_Name { get; set; }
    }
}
namespace PMS.Database
{
    using System;
    
    public partial class SSP_GetCustomerInvoicesByProject_Result
    {
        public int Id { get; set; }
        public string Invoice_number { get; set; }
        public decimal tax_amount { get; set; }
        public Nullable<bool> is_tax { get; set; }
        public Nullable<decimal> tax { get; set; }
        public Nullable<decimal> item_amount { get; set; }
        public Nullable<int> project_id { get; set; }
        public string PaymentAmount { get; set; }
    }
}
namespace PMS.Database
{
    using System;
    
    public partial class SSP_GetInvoiceList_Result
    {
        public int Id { get; set; }
        public string invoice_number { get; set; }
        public int project_id { get; set; }
        public Nullable<decimal> InvoiceAmount { get; set; }
        public decimal payment_amt { get; set; }
        public int payment_Count { get; set; }
        public Nullable<decimal> agreed_amt { get; set; }
    }
}
namespace PMS.Database
{
    using System;
    
    public partial class SSP_GetLoanProjectsDetailsByLoanId_Result
    {
        public int Id { get; set; }
        public int loan_Id { get; set; }
        public decimal amount { get; set; }
        public int project_id { get; set; }
        public string project_name { get; set; }
    }
}
namespace PMS.Database
{
    using System;
    
    public partial class SSP_GetPaymentDetails_Result
    {
        public Nullable<decimal> payment_amount { get; set; }
        public Nullable<decimal> agreed_amount { get; set; }
        public string invoice_number { get; set; }
        public Nullable<System.DateTime> payment_date { get; set; }
        public decimal amount { get; set; }
    }
}
namespace PMS.Database
{
    using System;
    
    public partial class SSP_GetSalesmenAndUser_Result
    {
        public string id { get; set; }
        public string Name { get; set; }
    }
}
namespace PMS.Database
{
    using System;
    
    public partial class SSP_Invoices_Result
    {
        public int Id { get; set; }
        public string Invoice_number { get; set; }
        public decimal tax_amount { get; set; }
        public System.DateTime Invoicedate { get; set; }
        public string Invoice_date { get; set; }
        public string salesmen_name { get; set; }
        public string customer_name { get; set; }
        public string CreatedUpdated { get; set; }
        public string company_name { get; set; }
        public decimal tax { get; set; }
        public Nullable<bool> is_tax { get; set; }
        public Nullable<long> Rk { get; set; }
        public Nullable<long> TotalRecords { get; set; }
        public string address { get; set; }
        public string Total { get; set; }
        public string Items { get; set; }
    }
}
namespace PMS.Database
{
    using System;
    
    public partial class SSP_InvoiceWithAndWithoutPayment_Result
    {
        public string Invoice_date { get; set; }
        public string salesmen_name { get; set; }
        public string branch_name { get; set; }
        public string mobile { get; set; }
        public string phone { get; set; }
        public string name1 { get; set; }
        public string invoice_numbers { get; set; }
        public string invoice_amount_items { get; set; }
        public Nullable<bool> is_tax { get; set; }
        public decimal tax { get; set; }
        public decimal tax_amount { get; set; }
        public int invoiceId { get; set; }
    }
}
namespace PMS.Database
{
    using System;
    
    public partial class SSP_Loan_Result
    {
        public Nullable<long> Rk { get; set; }
        public int Id { get; set; }
        public string loan_date { get; set; }
        public System.DateTime LoanDate { get; set; }
        public string person_name { get; set; }
        public string mode_of_payment { get; set; }
        public int rec_type { get; set; }
        public string bank_name { get; set; }
        public decimal amount { get; set; }
        public string CreatedUpdated { get; set; }
        public Nullable<long> TotalRecords { get; set; }
    }
}
namespace PMS.Database
{
    using System;
    
    public partial class SSP_LoanReport_Result
    {
        public System.DateTime LoanDate { get; set; }
        public string purpose { get; set; }
        public decimal amount { get; set; }
        public int rec_type { get; set; }
        public decimal TotalBalance { get; set; }
        public string supplier_name { get; set; }
        public string mode_of_payment { get; set; }
        public string bank_name { get; set; }
        public string cheque_number { get; set; }
        public string ProjectsDetail { get; set; }
    }
}
namespace PMS.Database
{
    using System;
    
    public partial class SSP_PaymentById_Result
    {
        public long id { get; set; }
        public Nullable<System.DateTime> payment_date { get; set; }
        public long supplier_id { get; set; }
        public int bank_id { get; set; }
        public string cheque_number { get; set; }
        public Nullable<decimal> rebate_amount { get; set; }
        public Nullable<decimal> paid_amount { get; set; }
        public string remarks { get; set; }
        public System.DateTime created_date { get; set; }
        public Nullable<System.Guid> created_by { get; set; }
        public System.DateTime modified_date { get; set; }
        public Nullable<System.Guid> modified_by { get; set; }
        public Nullable<int> payment_mode { get; set; }
        public bool isactive { get; set; }
        public string supplier_name { get; set; }
        public string Paymode { get; set; }
        public string branch_name { get; set; }
        public string address1 { get; set; }
        public string phone { get; set; }
        public string zip_code { get; set; }
        public string bank_name { get; set; }
    }
}
namespace PMS.Database
{
    using System;
    
    public partial class SSP_PaymentDetailsForSMS_Result
    {
        public string date_amount { get; set; }
        public string cheque_details { get; set; }
        public string mobile { get; set; }
        public string totalPayment { get; set; }
        public string branchAddress { get; set; }
        public string accountNo { get; set; }
    }
}
namespace PMS.Database
{
    using System;
    
    public partial class SSP_PaymentReport_Result
    {
        public string payment_date { get; set; }
        public string bank { get; set; }
        public Nullable<decimal> rebate_amount { get; set; }
        public Nullable<decimal> payment_amount { get; set; }
        public string supplier_name { get; set; }
        public string cheque_number { get; set; }
        public Nullable<decimal> paid_amount { get; set; }
    }
}
namespace PMS.Database
{
    using System;
    
    public partial class SSP_Payments_Result
    {
        public long id { get; set; }
        public string payment_date { get; set; }
        public Nullable<System.DateTime> paymentdate { get; set; }
        public string project_name { get; set; }
        public string supplier_name { get; set; }
        public string cheque_number { get; set; }
        public string remarks { get; set; }
        public string CreatedUpdated { get; set; }
        public string PaymentDetailItem { get; set; }
        public string PaymentDetailItemSearch { get; set; }
        public Nullable<long> Rk { get; set; }
        public Nullable<long> TotalRecords { get; set; }
    }
}
namespace PMS.Database
{
    using System;
    
    public partial class SSP_Print_DesignerInvoices_Result
    {
        public int Id { get; set; }
        public System.DateTime Invoice_date { get; set; }
        public string Designer_name { get; set; }
        public string payment_term { get; set; }
        public Nullable<int> payment_days { get; set; }
        public string contract_type { get; set; }
        public string Invoice_number { get; set; }
        public decimal tax { get; set; }
        public Nullable<bool> is_tax { get; set; }
        public string company_name { get; set; }
        public string address1 { get; set; }
        public string reg_no { get; set; }
        public string fax { get; set; }
        public string phone { get; set; }
        public string bank_name { get; set; }
        public string bank_address { get; set; }
        public string account_number { get; set; }
        public string branch_code { get; set; }
        public string bank_code { get; set; }
        public string swif_code { get; set; }
        public Nullable<decimal> tax_amount { get; set; }
    }
}
