//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PMS.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_supplierinvoice_items
    {
        public int Id { get; set; }
        public int invoice_id { get; set; }
        public int salesperson_id { get; set; }
        public int project_id { get; set; }
        public string invoice_number { get; set; }
        public Nullable<decimal> gst { get; set; }
        public Nullable<decimal> invoice_amt_without_gst { get; set; }
        public Nullable<decimal> invoice_amt_with_gst { get; set; }
        public Nullable<decimal> agreed_amt_without_gst { get; set; }
        public Nullable<decimal> agreed_amt { get; set; }
    }
}
