//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PMS.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_supplier_invoice
    {
        public int Id { get; set; }
        public Nullable<int> Company_id { get; set; }
        public System.DateTime invoice_date { get; set; }
        public int supplier_id { get; set; }
        public System.DateTime creation_date { get; set; }
        public System.Guid created_by { get; set; }
        public System.DateTime modification_date { get; set; }
        public System.Guid modified_by { get; set; }
    }
}
